### ISSUE TITLE
Problem when excuate mt5linux on wine

### ISSUE THREAD

**Issue by guslijif** [lucas-campagna/mt5linux#17]
Hi, here is my environment

Ubuntu 22.04.3 LTS
wine-8.0.2

Windows side:
Python 3.8.3 
mt5linux 
MetaTrader5 python package 

Ubuntu side:
Python 3.10.12
mt5linux 
MetaTrader5 running on wine

When I excuate following commend in wine(Step2):

`python -m mt5linux Z:\CostGuardianProject\win-py\python.exe`

I got this following error

`Traceback (most recent call last):
  File "Z:\CostGuardianProject\win-py\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "Z:\CostGuardianProject\win-py\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "Z:\CostGuardianProject\win-py\lib\site-packages\mt5linux\__main__.py", line 176, in <m
odule>
    main()
  File "Z:\CostGuardianProject\win-py\lib\site-packages\mt5linux\__main__.py", line 161, in ma
in
    Popen(['mkdir','-p',server_dir]).wait()
  File "Z:\CostGuardianProject\win-py\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "Z:\CostGuardianProject\win-py\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Can not find file`

**Comment by guslijif** [comment]
should close 

fix method run the cmd in shell
