### ISSUE TITLE
Not install

### ISSUE THREAD

**Issue by ulissispereira** [lucas-campagna/mt5linux#20]
INFO: pip is still looking at multiple versions of mt5linux to determine which version is compatible with other requirements. This could take a while.
  Using cached mt5linux-0.1.1.tar.gz (30 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-uzchz0d5/mt5linux_fdf7615c085642fabefb8d8899451801/setup.py", line 10, in <module>
          install_requires=open('requirements.txt','r').read().split('\n'),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by karuisaba** [comment]
I had a similar error. 
The issue was caused by the fact that mt5linux requires a version of numpy that is not compatible with Python 3.11 and later. 
Therefore, I downgraded Python to version 3.10 and installed packages that are compatible with numpy==1.21.4.
```
// Python version 3.10.14
pip install mt5linux
pip install numpy==1.21.4 pandas
```

**Comment by hpdeandrade** [comment]
Check out my [fork](https://github.com/hpdeandrade/mt5linux) in case you want to stick with a newer python version. It works with Python 3.13.
