### ISSUE TITLE
Whenever i Try to login to my trading account i got error result expired ... But it actually log me in To mt5 

### ISSUE THREAD

**Issue by umerweb** [lucas-campagna/mt5linux#22]
Traceback (most recent call last):
  File "/home/mehar-umer/PycharmProjects/pythonProject1/bot.py", line 14, in <module>
    initialize = mt5.initialize(login=account_no,password=password,server=server)
  File "/home/mehar-umer/PycharmProjects/pythonProject1/venv/lib/python3.8/site-packages/mt5linux/__init__.py", line 464, in initialize
    return self.__conn.eval(code)
  File "/home/mehar-umer/PycharmProjects/pythonProject1/venv/lib/python3.8/site-packages/rpyc/core/netref.py", line 239, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/home/mehar-umer/PycharmProjects/pythonProject1/venv/lib/python3.8/site-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/home/mehar-umer/PycharmProjects/pythonProject1/venv/lib/python3.8/site-packages/rpyc/core/protocol.py", line 744, in sync_request
    return _async_res.value
  File "/home/mehar-umer/PycharmProjects/pythonProject1/venv/lib/python3.8/site-packages/rpyc/core/async_.py", line 109, in value
    self.wait()
  File "/home/mehar-umer/PycharmProjects/pythonProject1/venv/lib/python3.8/site-packages/rpyc/core/async_.py", line 55, in wait
    raise AsyncResultTimeout("result expired")
TimeoutError: result expired

**Comment by EKivutha** [comment]
Getting the same error on initialize
>>> mt5.initialize()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/config/.local/lib/python3.9/site-packages/mt5linux/__init__.py", line 464, in initialize
    return self.__conn.eval(code)
  File "/config/.local/lib/python3.9/site-packages/rpyc/core/netref.py", line 240, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/config/.local/lib/python3.9/site-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/config/.local/lib/python3.9/site-packages/rpyc/core/protocol.py", line 473, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/config/.local/lib/python3.9/site-packages/rpyc/core/async_.py", line 100, in value
    self.wait()
  File "/config/.local/lib/python3.9/site-packages/rpyc/core/async_.py", line 49, in wait
    raise AsyncResultTimeout("result expired")
TimeoutError: result expired

**Comment by umerweb** [comment]
did you find any solution?

**Comment by EKivutha** [comment]
Use this 
mt5.initialize(login=account_no,password=password,server=server)
don't equate to anything

**Comment by umerweb** [comment]
I also didn't worked

**Comment by Pedanfer** [comment]
Is this package alive anymore?

**Comment by hpdeandrade** [comment]
> Is this package alive anymore?

I forked this project [pymt5linux](https://github.com/hpdeandrade/pymt5linux), hope it helps.
