### ISSUE TITLE
I can use the library mt5_linux ?

### ISSUE THREAD

**Issue by boujrafh** [lucas-campagna/mt5linux#23]
Hello,

thank you for your post, it's work fine.

The docker image it's work fine but i can install le library mt5_linux

I have a vps debian 12, could you help me for this

`
(my-virtual-env) root@vmi2123874:/trading/MetaTrader5-Docker-Image# pip3 install mt5linux
Collecting mt5linux
  Using cached mt5linux-0.1.9-py3-none-any.whl.metadata (2.8 kB)
Collecting bleach==4.1.0 (from mt5linux)
  Using cached bleach-4.1.0-py2.py3-none-any.whl.metadata (24 kB)
Collecting certifi==2021.10.8 (from mt5linux)
  Using cached certifi-2021.10.8-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting cffi==1.15.0 (from mt5linux)
  Using cached cffi-1.15.0.tar.gz (484 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting charset-normalizer==2.0.7 (from mt5linux)
  Using cached charset_normalizer-2.0.7-py3-none-any.whl.metadata (11 kB)
Collecting colorama==0.4.4 (from mt5linux)
  Using cached colorama-0.4.4-py2.py3-none-any.whl.metadata (14 kB)
Collecting cryptography==35.0.0 (from mt5linux)
  Using cached cryptography-35.0.0-cp36-abi3-manylinux_2_24_x86_64.whl.metadata (5.4 kB)
Collecting docutils==0.18 (from mt5linux)
  Using cached docutils-0.18-py2.py3-none-any.whl.metadata (2.9 kB)
Collecting idna==3.3 (from mt5linux)
  Using cached idna-3.3-py3-none-any.whl.metadata (9.8 kB)
Collecting importlib-metadata==4.8.1 (from mt5linux)
  Using cached importlib_metadata-4.8.1-py3-none-any.whl.metadata (4.0 kB)
Collecting jeepney==0.7.1 (from mt5linux)
  Using cached jeepney-0.7.1-py3-none-any.whl.metadata (1.3 kB)
Collecting keyring==23.2.1 (from mt5linux)
  Using cached keyring-23.2.1-py3-none-any.whl.metadata (18 kB)
INFO: pip is looking at multiple versions of mt5linux to determine which version is compatible with other requirements. This could take a while.
Collecting mt5linux
  Using cached mt5linux-0.1.8.tar.gz (61 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached mt5linux-0.1.7.tar.gz (61 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached mt5linux-0.1.6-py3-none-any.whl.metadata (2.3 kB)
  Using cached mt5linux-0.1.5-py3-none-any.whl.metadata (2.3 kB)
  Using cached mt5linux-0.1.4-py3-none-any.whl.metadata (2.3 kB)
  Using cached mt5linux-0.1.3-py3-none-any.whl.metadata (2.3 kB)
  Using cached mt5linux-0.1.2-py3-none-any.whl.metadata (2.3 kB)
INFO: pip is still looking at multiple versions of mt5linux to determine which version is compatible with other requirements. This could take a while.
  Using cached mt5linux-0.1.1.tar.gz (30 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/trading/MetaTrader5-Docker-Image/my-virtual-env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/trading/MetaTrader5-Docker-Image/my-virtual-env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/trading/MetaTrader5-Docker-Image/my-virtual-env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-v5zzuf_x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-v5zzuf_x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-v5zzuf_x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-v5zzuf_x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 10, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem
`

**Comment by boujrafh** [comment]
I found the problem because i used the python 3.12 version et for this library we need python 3.9.13
