### ISSUE TITLE
Issue with datetime module

### ISSUE THREAD

**Issue by Amineyv** [lucas-campagna/mt5linux#3]

**Comment by Amineyv** [comment]
Hey Lucas,

I have a problem using the server.

I am using mt5.copy_ticks_from() but in the "date_from" parameter, writing ..., datetime(2022,4,30,14), ... it catches an error that i do not know how to solve. 
My code:
`euroaud_ticks = mt5.copy_ticks_from("EURAUD", datetime(2020, 1, 28, 13), 1000, mt5.COPY_TICKS_ALL)
`
The error in console:
`
Traceback (most recent call last):
  File "trade.py", line 34, in <module>
    euroaud_ticks = mt5.copy_ticks_from(
  File "/home/amineyv/.local/share/virtualenvs/order_execution-w-znQGb-/lib/python3.8/site-packages/mt5linux/__init__.py", line 2445, in copy_ticks_from
    return rpyc.utils.classic.obtain(self.__conn.eval(code))
  File "/home/amineyv/.local/share/virtualenvs/order_execution-w-znQGb-/lib/python3.8/site-packages/rpyc/core/netref.py", line 240, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/home/amineyv/.local/share/virtualenvs/order_execution-w-znQGb-/lib/python3.8/site-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/home/amineyv/.local/share/virtualenvs/order_execution-w-znQGb-/lib/python3.8/site-packages/rpyc/core/protocol.py", line 473, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/home/amineyv/.local/share/virtualenvs/order_execution-w-znQGb-/lib/python3.8/site-packages/rpyc/core/async_.py", line 102, in value
    raise self._obj
NameError: name 'datetime' is not defined
`

The error on wine edition python:
`
DEBUG:SLAVE/18812:Exception caught
========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "Z:\home\amineyv\wine\PythonWindows\lib\site-packages\rpyc\core\protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "Z:\home\amineyv\wine\PythonWindows\lib\site-packages\rpyc\core\protocol.py", line 593, in _handle_call
    return obj(*args, **dict(kwargs))
  File "Z:\home\amineyv\wine\PythonWindows\lib\site-packages\rpyc\core\service.py", line 159, in eval
    return eval(text, self.namespace)
  File "<string>", line 1, in <module>
NameError: name 'datetime' is not defined
`

Can anyone please help me on solving this issue?
Any ideas on how to pass values to the server is much appreciated.

Thanks.

**Comment by lucas-campagna** [comment]
Hi, Amineyv!

I'm working on this bug.

For now, try to run `mt5.execute('import datetime')`.

This errors arises because datetime wasn't imported at the other side (python windows).

**Comment by Amineyv** [comment]
Thanks a lot dear @lucas-campagna.

**Comment by awesome-experts** [comment]
try to work around the problem by add ```mt5.execute('import datetime')```, but another problem occured:

```python
mt5.execute('import datetime')
timezone = pytz.timezone("Etc/UTC")
utc_from = datetime(2022, 9, 10, tzinfo=timezone)
utc_to = datetime(2022, 9, 11, hour = 13, tzinfo=timezone)
rates2 = mt5.copy_rates_range("XAUUSD", mt5.TIMEFRAME_M5, utc_from, utc_to)
```

error:
```
Traceback (most recent call last):
  File "/Users/vivia/GitHub/l2/test_case/mt5linux_test.py", line 62, in <module>
    rates2 = mt5.copy_rates_range("XAUUSD", mt5.TIMEFRAME_M5, utc_from, utc_to)
  File "/Users/vivia/GitHub/l2/venv/lib/python3.10/site-packages/mt5linux/__init__.py", line 2290, in copy_rates_range
    return rpyc.utils.classic.obtain(self.__conn.eval(code))
  File "/Users/vivia/GitHub/l2/venv/lib/python3.10/site-packages/rpyc/core/netref.py", line 240, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/Users/vivia/GitHub/l2/venv/lib/python3.10/site-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/Users/vivia/GitHub/l2/venv/lib/python3.10/site-packages/rpyc/core/protocol.py", line 473, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/Users/vivia/GitHub/l2/venv/lib/python3.10/site-packages/rpyc/core/async_.py", line 102, in value
    raise self._obj
  File "<string>", line 1
    mt5.copy_rates_range("XAUUSD", 5, datetime.datetime(2022, 9, 10, 8, 0, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'CST')), 2022-09-11 13:00:00+00:00)
                                                                                                                                                     ^
_get_exception_class.<locals>.Derived: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```

**Comment by james-coder** [comment]
@lucas-campagna Can't the `mt5.execute('import datetime')` be done as a last step on `initialize()`?

@jhezjkp @lucas-campagna `repr()` needs to wrap `date_to` on line 2289 below. I grepped and this was the only one not done like this. Just a typo? 
https://github.com/lucas-campagna/mt5linux/blob/master/mt5linux/__init__.py#L2289

**Comment by tkhaltet** [comment]
@jhezjkp you should also do a `mt5.execute('import pytz')`

This code should work:

```python
mt5.execute('import datetime')
mt5.execute('import pytz')
timezone = pytz.timezone("Etc/UTC")
utc_from = datetime(2022, 9, 10, tzinfo=timezone)
utc_to = datetime(2022, 9, 11, hour = 13, tzinfo=timezone)
rates2 = mt5.copy_rates_range("XAUUSD", mt5.TIMEFRAME_M5, utc_from, utc_to)
```
